var sound1 = new Audio();
sound1.src = "Audio Sampler/Audio/ah-ha.mp3";
var sound2 = new Audio();
sound2.src = "Audio Sampler/Audio/back-of-the-net.mp3";
var sound3 = new Audio();
sound3.src = "Audio Sampler/Audio/bangoutoforder.mp3";
var sound4 = new Audio();
sound4.src = "Audio Sampler/Audio/dan.mp3";
var sound5 = new Audio();
sound5.src = "Audio Sampler/Audio/emailoftheevening.mp3";
var sound6 = new Audio();
sound6.src = "Audio Sampler/Audio/hellopartridge.mp3";
var sound7 = new Audio();
sound7.src = "Audio Sampler/Audio/iateascotchegg.mp3";
var sound8 = new Audio();
sound8.src = "Audio Sampler/Audio/imconfused.mp3";
var sound9 = new Audio();
sound9.src = "Audio Sampler/Audio/goal.mp3"
